export interface Institution {
  name: string;
  code?: string;
}

export const institutions: Institution[] = [
  { name: "Universidade de São Paulo (USP)", code: "USP" },
  { name: "Universidade Estadual de Campinas (UNICAMP)", code: "UNICAMP" },
  { name: "Universidade Estadual Paulista (UNESP)", code: "UNESP" },
  { name: "Universidade Federal de Minas Gerais (UFMG)", code: "UFMG" },
  { name: "Universidade Federal do Rio de Janeiro (UFRJ)", code: "UFRJ" },
  { name: "Pontifícia Universidade Católica (PUC)", code: "PUC" },
  { name: "Fundação Getúlio Vargas (FGV)", code: "FGV" },
  { name: "Insper", code: "INSPER" },
  { name: "Fundação Instituto de Administração (FIA)", code: "FIA" },
  { name: "Universidade Federal de São Paulo (UNIFESP)", code: "UNIFESP" },
  { name: "Universidade Federal do Rio Grande do Sul (UFRGS)", code: "UFRGS" },
  { name: "Universidade Federal de Santa Catarina (UFSC)", code: "UFSC" },
  { name: "Universidade Federal do Paraná (UFPR)", code: "UFPR" },
  { name: "Universidade Federal de Pernambuco (UFPE)", code: "UFPE" },
  { name: "Universidade Federal da Bahia (UFBA)", code: "UFBA" },
  { name: "Universidade Federal do Ceará (UFC)", code: "UFC" },
  { name: "Universidade Federal de Brasília (UNB)", code: "UNB" },
  { name: "Universidade Federal Fluminense (UFF)", code: "UFF" },
  { name: "Universidade Estadual do Rio de Janeiro (UERJ)", code: "UERJ" },
  { name: "Universidade Federal de Goiás (UFG)", code: "UFG" },
  { name: "Universidade Federal de Viçosa (UFV)", code: "UFV" },
  { name: "Universidade Federal de Uberlândia (UFU)", code: "UFU" },
  { name: "Universidade Estadual de Maringá (UEM)", code: "UEM" },
  { name: "Universidade Estadual de Londrina (UEL)", code: "UEL" },
  { name: "Universidade Federal de São Carlos (UFSCar)", code: "UFSCar" },
  { name: "Universidade Federal do ABC (UFABC)", code: "UFABC" },
  { name: "Universidade Federal de Itajubá (UNIFEI)", code: "UNIFEI" },
  { name: "Instituto Tecnológico de Aeronáutica (ITA)", code: "ITA" },
  { name: "Instituto Militar de Engenharia (IME)", code: "IME" },
  { name: "Escola Superior de Propaganda e Marketing (ESPM)", code: "ESPM" },
  { name: "Faculdade de Economia, Administração e Contabilidade (FEA-USP)", code: "FEA-USP" },
  { name: "Escola Politécnica da USP (POLI-USP)", code: "POLI-USP" },
  { name: "Faculdade de Medicina da USP (FMUSP)", code: "FMUSP" },
  { name: "Escola de Administração de Empresas de São Paulo (EAESP-FGV)", code: "EAESP-FGV" },
  { name: "Fundação Dom Cabral (FDC)", code: "FDC" },
  { name: "IBMEC", code: "IBMEC" },
  { name: "Universidade Anhembi Morumbi", code: "UAM" },
  { name: "Universidade Presbiteriana Mackenzie", code: "MACKENZIE" },
  { name: "Pontifícia Universidade Católica de São Paulo (PUC-SP)", code: "PUC-SP" },
  { name: "Pontifícia Universidade Católica do Rio de Janeiro (PUC-RJ)", code: "PUC-RJ" },
  { name: "Pontifícia Universidade Católica de Minas Gerais (PUC-MG)", code: "PUC-MG" },
  { name: "Universidade Federal Rural do Rio de Janeiro (UFRRJ)", code: "UFRRJ" },
  { name: "Universidade Federal do Estado do Rio de Janeiro (UNIRIO)", code: "UNIRIO" },
  { name: "Universidade Estadual de Feira de Santana (UEFS)", code: "UEFS" },
  { name: "Universidade Federal do Rio Grande do Norte (UFRN)", code: "UFRN" },
  { name: "Universidade Federal de Alagoas (UFAL)", code: "UFAL" },
  { name: "Universidade Federal de Sergipe (UFS)", code: "UFS" },
  { name: "Universidade Federal do Pará (UFPA)", code: "UFPA" },
  { name: "Universidade Federal do Amazonas (UFAM)", code: "UFAM" },
  { name: "Universidade Federal de Rondônia (UNIR)", code: "UNIR" },
  { name: "Universidade Federal de Roraima (UFRR)", code: "UFRR" },
  { name: "Universidade Federal do Acre (UFAC)", code: "UFAC" },
  { name: "Universidade Federal do Amapá (UNIFAP)", code: "UNIFAP" },
  { name: "Universidade Federal do Tocantins (UFT)", code: "UFT" },
  { name: "Universidade Federal de Mato Grosso (UFMT)", code: "UFMT" },
  { name: "Universidade Federal de Mato Grosso do Sul (UFMS)", code: "UFMS" },
  { name: "Universidade Federal do Espírito Santo (UFES)", code: "UFES" },
  { name: "Universidade Federal do Maranhão (UFMA)", code: "UFMA" },
  { name: "Universidade Federal do Piauí (UFPI)", code: "UFPI" },
  { name: "Universidade Federal de Campina Grande (UFCG)", code: "UFCG" },
  { name: "Universidade Federal da Paraíba (UFPB)", code: "UFPB" },
  { name: "Universidade Federal de Santa Maria (UFSM)", code: "UFSM" },
  { name: "Universidade Federal do Rio Grande (FURG)", code: "FURG" },
  { name: "Universidade Federal de Pelotas (UFPel)", code: "UFPel" },
  { name: "Universidade Federal de Juiz de Fora (UFJF)", code: "UFJF" },
  { name: "Universidade Federal de Lavras (UFLA)", code: "UFLA" },
  { name: "Universidade Federal de Ouro Preto (UFOP)", code: "UFOP" },
  { name: "Universidade Federal de São João del-Rei (UFSJ)", code: "UFSJ" },
  { name: "Universidade Federal do Triângulo Mineiro (UFTM)", code: "UFTM" },
  { name: "Universidade Federal de Alfenas (UNIFAL)", code: "UNIFAL" },
  { name: "Universidade Estadual de Ponta Grossa (UEPG)", code: "UEPG" },
  { name: "Universidade Estadual do Oeste do Paraná (UNIOESTE)", code: "UNIOESTE" },
  { name: "Universidade Estadual do Centro-Oeste (UNICENTRO)", code: "UNICENTRO" },
  { name: "Universidade Estadual de Santa Catarina (UDESC)", code: "UDESC" },
  { name: "Universidade Estadual do Rio Grande do Sul (UERGS)", code: "UERGS" },
  { name: "Universidade Estadual do Ceará (UECE)", code: "UECE" },
  { name: "Universidade Estadual do Piauí (UESPI)", code: "UESPI" },
  { name: "Universidade Estadual da Paraíba (UEPB)", code: "UEPB" },
  { name: "Universidade Estadual de Goiás (UEG)", code: "UEG" },
  { name: "Universidade Estadual de Mato Grosso do Sul (UEMS)", code: "UEMS" },
  { name: "Universidade Estadual de Montes Claros (UNIMONTES)", code: "UNIMONTES" },
  { name: "Universidade Estadual do Sudoeste da Bahia (UESB)", code: "UESB" },
  { name: "Universidade Estadual do Norte Fluminense (UENF)", code: "UENF" },
  { name: "Universidade Estadual do Maranhão (UEMA)", code: "UEMA" },
  { name: "Universidade Estadual do Amazonas (UEA)", code: "UEA" },
  { name: "Universidade Estadual de Roraima (UERR)", code: "UERR" },
  { name: "Universidade Estadual do Acre (UEAC)", code: "UEAC" },
  { name: "Universidade Estadual do Amapá (UEAP)", code: "UEAP" },
  { name: "Universidade Estadual do Tocantins (UNITINS)", code: "UNITINS" },
  { name: "Universidade Estadual de Rondônia (UNIR)", code: "UNIR" },
  { name: "Universidade Estadual de Mato Grosso (UNEMAT)", code: "UNEMAT" },
  { name: "Universidade Estadual do Pará (UEPA)", code: "UEPA" },
  { name: "Universidade Estadual de Alagoas (UNEAL)", code: "UNEAL" },
  { name: "Universidade Estadual de Sergipe (UESE)", code: "UESE" },
  { name: "Universidade Estadual do Rio Grande do Norte (UERN)", code: "UERN" },
  { name: "Universidade Estadual do Vale do Acaraú (UVA)", code: "UVA" },
  { name: "Universidade Estadual de Santa Cruz (UESC)", code: "UESC" },
].sort((a, b) => a.name.localeCompare(b.name, "pt-BR"));
